"""empty message

Revision ID: 07fc1ddd31cc
Revises: d0e6d96ed657
Create Date: 2017-07-13 20:32:27.191644

"""

# revision identifiers, used by Alembic.
revision = '07fc1ddd31cc'
down_revision = 'd0e6d96ed657'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('challonge_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_team_challonge_id'), 'team', ['challonge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_challonge_id'), table_name='team')
    op.drop_column('team', 'challonge_id')
    # ### end Alembic commands ###
