"""empty message

Revision ID: 51b37c936640
Revises: 764e59ea726c
Create Date: 2017-07-14 23:28:05.194348

"""

# revision identifiers, used by Alembic.
revision = '51b37c936640'
down_revision = '764e59ea726c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('open_join', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_team_open_join'), 'team', ['open_join'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_open_join'), table_name='team')
    op.drop_column('team', 'open_join')
    # ### end Alembic commands ###
