"""empty message

Revision ID: 764e59ea726c
Revises: d14fe2819dea
Create Date: 2017-07-14 18:38:09.725239

"""

# revision identifiers, used by Alembic.
revision = '764e59ea726c'
down_revision = 'd14fe2819dea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_match')
    op.add_column('match', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'tournament', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'tournament_id')
    op.create_table('tournament_match',
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name='tournament_match_match_id_fkey'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name='tournament_match_tournament_id_fkey')
    )
    # ### end Alembic commands ###
