"""empty message

Revision ID: ac397b9380d5
Revises: 48c5a5bb98cf
Create Date: 2017-07-11 22:21:16.269197

"""

# revision identifiers, used by Alembic.
revision = 'ac397b9380d5'
down_revision = '48c5a5bb98cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('url', sa.String(length=60), nullable=True),
    sa.Column('challonge_id', sa.Integer(), nullable=True),
    sa.Column('challonge_data', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_server_public_server'), 'game_server', ['public_server'], unique=False)
    op.create_index(op.f('ix_match_server_id'), 'match', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_server_id'), table_name='match')
    op.drop_index(op.f('ix_game_server_public_server'), table_name='game_server')
    op.drop_table('tournament')
    # ### end Alembic commands ###
