"""empty message

Revision ID: ded2e28b5186
Revises: ac397b9380d5
Create Date: 2017-07-11 22:36:23.359631

"""

# revision identifiers, used by Alembic.
revision = 'ded2e28b5186'
down_revision = 'ac397b9380d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_match',
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], )
    )
    op.create_table('tournament_team',
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_team')
    op.drop_table('tournament_match')
    # ### end Alembic commands ###
