defaults = {
    'LOG_PATH': None,
    'DEBUG': False,
    'TESTING': False,
    'SQLALCHEMY_DATABASE_URI': 'mysql://user:password@host/db',
    'SQLALCHEMY_TRACK_MODIFICATIONS': False,
    'STEAM_API_KEY': '???',
    'CHALLONGE_API_KEY': '???',
    'SECRET_KEY': '???',
    'USER_MAX_SERVERS': 10,
    'USER_MAX_TEAMS': 100,
    'USER_MAX_MATCHES': 1000,
    'USER_MAX_TOURNAMENTS': 100,
    'BRAND': 'Get5 Web Panel',
    'DEFAULT_PAGE': '/matches',
    'DEFAULT_COUNTRY_CODE': 'eu',
    'ADMINS_ACCESS_ALL_MATCHES': False,
    'ADMINS_ACCESS_ALL_TOURNAMENTS': True,
    'CREATE_MATCH_TITLE_TEXT': False,
    'CREATE_TOURNAMENT_NAME_TEXT': False,
    'WHITELISTED_IDS': [],
    'ADMIN_IDS': [],
    'MAPLIST': [
        'de_cache',
        'de_cbble',
        'de_inferno',
        'de_mirage',
        'de_nuke',
        'de_overpass',
        'de_train',
        'de_dust2',
        'de_season'
    ],
    'DEFAULT_MAPLIST': [
        'de_cache',
        'de_cbble',
        'de_inferno',
        'de_mirage',
        'de_nuke',
        'de_overpass',
        'de_train',
    ],
}
